---
- name: Check argocd namespace exists
  ansible.builtin.shell: k3s kubectl get namespace
  register: namespace_contents

- debug: msg="{{ namespace_contents.stdout.find('baaaaaa') }}"

- name: Set namespace
  ansible.builtin.command:
    cmd: >
      k3s kubectl create namespace {{ argocd_namespace }}
  when: namespace_contents.stdout.find('argocd') == -1

- name: Copy argo install manifest
  ansible.builtin.template:
    src: "k3s-argo-install.yaml.j2"
    dest: "/tmp/argo-install.yaml"
    owner: root
    group: root
    mode: 0644

- name: Install ArgoCD
  ansible.builtin.command:
    cmd: >
      k3s kubectl apply -n argocd -f /tmp/argo-install.yaml

- name: Download ArgoCD CLI
  ansible.builtin.get_url:
    url: https://github.com/argoproj/argo-cd/releases/download/{{ argocd_version }}/argocd-linux-amd64
    timeout: 120
    dest: /usr/local/bin/argocd
    owner: root
    group: root
    mode: a+x

- name: Copy argo appset manifest
  ansible.builtin.template:
    src: "k3s-argo-appset.yaml.j2"
    dest: "/tmp/argo-appset.yaml"
    owner: root
    group: root
    mode: 0644

- name: Apply appset manifest
  ansible.builtin.command:
    cmd: >
      k3s kubectl apply -n argocd -f /tmp/argo-appset.yaml
  