- name: Copy argo appset manifest
  ansible.builtin.copy:
    src: "argo-appset.yaml"
    dest: "/tmp/argo-appset.yaml"
    owner: root
    group: root
    mode: 0644

- name: Create data folder
  ansible.builtin.file:
    mode: 0644
    owner: root
    group: root
    path: /opt/data
    state: directory


- name: Set argcd context
  ansible.builtin.command:
    cmd: >
      k3s kubectl config set-context --current --namespace argocd

- name: Wait for default project to be available
  ansible.builtin.command:
    cmd: >
      argocd proj list --core
  register: cmd_argo_project
  become: false
  until: cmd_argo_project.stdout.find('default') != -1

- name: Apply appset manifest
  ansible.builtin.command:
    cmd: >
      k3s kubectl apply -n argocd -f /tmp/argo-appset.yaml